### ISSUE TITLE
ubuntu 20.0.4.5 lts

### ISSUE THREAD

**Issue by hhumas** [Moji14/PartKeepr-installation-script#1]
hi , can i use this script on ubuntu 20.0.4

**Comment by Moji14** [comment]
Hi,
It's supposed that it should work but, due to modifications on new versions of Apache, PHP, MySQL it's possible the installation may have some compatibility issues. 
Also, the script was made for a fresh OS installation, if you already have an installed Ubuntu with the components required being used with specific configurations you may get some trouble as well.
This script was intended for academic and learning purposes. 
I encourage you to try to install it on a fresh OS system and then if you get in trouble you can post and issue on PartKeepr GitHub issue tracker
https://github.com/partkeepr/PartKeepr/issues
Good luck!
